### ISSUE TITLE
Game.ini

### ISSUE THREAD

**Issue by molnarviktor86** [jkread/arkserver#4]
Hi,

It seems like the gameusersettings.ini are applied on my dedicated server, but no matter what I do the Game.ini changes are just not working.

[/script/shootergame.shootergamemode]
MatingIntervalMultiplier=0.1
EggHatchSpeedMultiplier=20
BabyMatureSpeedMultiplier=10
BabyCuddleIntervalMultiplier=0.1

What am I missing here? FezVrasta's configuration parameter's again point to changes that has to put in gameusersettings.ini

**Comment by jkread** [comment]
I haven't messed with Game.ini much. Give me a bit to look into it.

**Comment by jkread** [comment]
Place your custom Game.ini in /ark/config and it will get linked where it needs to on launch. Same with the others listed in the readme, verified to work.
